version: "3.9"
services:

  web-server:
    build:
      context: server
      dockerfile: server/Dockerfile
    container_name: web-server_app
    ports:
      - "3000:3000"
    restart: always
      
  web-client:
    build:
      context: client
      dockerfile: client/Dockerfile
    container_name: web-client_app
    ports:
      - "8080:80"
    restart: always
