version: "3.9"

services:
  web-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
      
  web-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
