version: "3.9"
services:

  web-server:
    build: server
    container_name: web-server_app
    ports:
      - "3000:3000"
    restart: always
  
  web-client:
    build: client
    container_name: web-client_app
    ports:
      - "3000:3000"
    restart: always
